# Generated by Django 6.0.1 on 2026-05-02 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name or Emoji', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=15)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('memory', models.CharField(blank=True, max_length=50)),
                ('battery_health', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('new', 'Yangi'), ('ideal', 'Ideal'), ('good', 'Yaxshi'), ('bad', "Ta'mir talab")], max_length=20)),
                ('location', models.CharField(default='Toshkent', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('images_json', models.JSONField(blank=True, default=list, help_text='Multiple image URLs if any')),
                ('seller_phone', models.CharField(blank=True, max_length=20)),
                ('seller_telegram', models.CharField(blank=True, max_length=50)),
                ('is_approved', models.BooleanField(default=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='phones.category')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='phones.listing')),
            ],
            options={
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
