# Generated by Django 6.0.1 on 2026-05-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='branch',
            field=models.CharField(choices=[('malika', 'Malika'), ('chilonzor', 'Chilonzor')], default='malika', max_length=20),
        ),
    ]
