# Generated by Django 6.0.1 on 2026-05-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phone_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='booked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='booked_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
