# Generated by Django 6.0.1 on 2026-05-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_branch_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='body_condition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='defects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='replaced_parts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='listing',
            name='screen_condition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'Yangi'), ('ideal', 'Ideal'), ('good', 'Yaxshi'), ('bad', "Ta'mir talab")], default='ideal', max_length=20),
        ),
    ]
