# Generated by Django 6.0.1 on 2026-05-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_listing_body_condition_listing_color_listing_defects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_sale',
            field=models.BooleanField(default=False, help_text='Aksiya/Chegirma'),
        ),
    ]
