# Generated by Django 6.0.1 on 2026-05-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_priceassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_visits', models.IntegerField(default=0)),
                ('region_stats', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-is_sale', '-created_at']},
        ),
        migrations.AddField(
            model_name='listing',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Aksiya uchun eski narx', max_digits=15, null=True),
        ),
    ]
