STRINGS = {
    'uz': {
        'start_welcome': "Assalomu alaykum! Markab Electronics botiga xush kelibsiz.\nIltimos, tilni tanlang:",
        'select_lang': "🇺🇿 O'zbek tili",
        'sub_required': "Botdan foydalanish uchun kanalimizga obuna bo'lishingiz shart!",
        'btn_sub': "Obuna bo'lish",
        'btn_check': "Tasdiqlash",
        'sub_error': "Siz hali kanalga obuna bo'lmagansiz. Iltimos, obuna bo'ling va qaytadan 'Tasdiqlash' tugmasini bosing.",
        'main_menu': "Asosiy menyu:",
        'btn_buy': "🛍 Telefon sotib olish",
        'btn_sell': "📱 Telefon sotish",
        'btn_price': "💰 Narxlatish",
        'btn_branches': "🏢 Bizning filiallar",
        'btn_miniapp': "🌐 Mini App",
        'btn_help': "ℹ️ Ma'lumot/Yordam",
        'btn_admin': "🔐 Admin Panel",
        'btn_open_miniapp': "🌐 Mini App'da ochish",
        'btn_continue_bot': "🤖 Botda davom etish",
        'btn_continue': "➡️ Davom etish",
        'prompt_choice': "✨ <b>Qanday usulda davom ettirishni xohlaysiz?</b>\n\n<i>Mini App tezroq va qulayroq, Bot esa bosqichma-bosqich yordam beradi.</i>",
        'prompt_color': "🎨 <b>Telefoningiz rangini tanlang:</b>",
        'prompt_cycles': "🔄 <b>Batareya tsiklini (cycles) kiriting (masalan: 150):</b>",
        'prompt_replaced_parts': "🔧 <b>Almashtirilgan qismlar:</b>\n\n<i>Almashtirilgan qismlarni belgilang va 'Davom etish' tugmasini bosing.</i>",
        'prompt_defects': "⚠️ <b>Nosozliklar:</b>\n\n<i>Nosozliklarni belgilang va 'Davom etish' tugmasini bosing.</i>",
        'btn_yes': "✅ Ha",
        'btn_no': "❌ Yo'q",
        'lbl_color': "Rangi",
        'lbl_cycles': "Tsikli",
        'btn_cancel': "❌ Bekor qilish",
        'btn_confirm': "✅ Tasdiqlash",
        'btn_share_contact': "📞 Raqamni ulashish",
        'btn_add_product': "➕ Mahsulot qo'shish",
        'btn_manage_branches': "🏢 Filiallarni boshqarish",
        'btn_delete_product': "🗑 Mahsulotni o'chirish",
        'btn_stats': "📊 Statistika",
        'btn_back': "⬅️ Orqaga",
        'btn_exit': "⬅️ Chiqish",
        'btn_add_branch': "➕ Yangi filial qo'shish",
        'btn_delete_branch': "❌ Filialni o'chirish",
        'btn_back_to_admin': "⬅️ Admin menyuga qaytish",
        'btn_set_price': "✍️ Narx yozish",
        'btn_approve': "✅ Tasdiqlash",
        'btn_counter': "🔄 Qarshi taklif",
        'btn_reject': "❌ Rad etish",
        'msg_deleted': "🗑 Mahsulot o'chirildi.",
        'msg_cancelled': "❌ Bekor qilindi.",
        'msg_success_add': "✅ Mahsulot muvaffaqiyatli qo'shildi!",
        'main_menu_info': "📱 Telefoningizni bozor narxida baholashingiz;\n🤝 Tez va oson sotishingiz;\n🛍 Sifatli telefonlarni sotib olishingiz mumkin.",
        'prompt_model': "📲 <b>Sotmoqchi bo'lgan iPhone modelini tanlang:</b>",
        'prompt_photos': "📸 <b>1 ta sifatli rasm yuklang:</b>",
        'prompt_battery': "🔋 <b>Batareya yomkostini kiriting (% da, masalan: 88):</b>",
        'prompt_memory': "💾 <b>Xotira hajmini tanlang:</b>",
        'prompt_screen_condition': "📱 <b>Ekran holati qanday?</b>",
        'prompt_body_condition': "📐 <b>Korpus (chetlari va orqasi) holati qanday?</b>",
        'prompt_region': "🌍 <b>Regionni tanlang:</b>",
        'prompt_box': "📦 <b>Karobka va hujjati bormi?</b>",
        'prompt_is_opened': "🛠 <b>Telefon ochilganmi, ustada bo'lganmi?</b>",
        'prompt_price': "💰 <b>Sotmoqchi bo'lgan narxingizni kiriting (masalan: 8 500 000 so'm yoki 8.5 mln):</b>",
        'prompt_description': "📝 <b>Telefon haqida qo'shimcha ma'lumot yozing (ixtiyoriy, 'O'tkazish' deb yozishingiz mumkin):</b>",
        'prompt_contact': "📞 <b>Bog'lanish uchun telefon raqamingizni yuboring:</b>",
        'prompt_confirm': "✨ <i>Barchasi to'g'rimi? Tasdiqlaysizmi?</i>",
        'summary_title': "<b>📋 E'loningiz ma'lumotlari:</b>",
        'sell_success': "✅ <b>Sizning e'loningiz qabul qilindi!</b>\n\nTelefoningizning taxminiy bozor narxi: <b>{price} mln so'm</b>.\n\nAdminlarimiz tez orada uni ko'rib chiqib, kanalga joylashadi.",
        'err_battery': "❌ Iltimos, haqiqiy foiz kiriting (1-100):",
        'lbl_model': "Model",
        'lbl_memory': "Xotira",
        'lbl_battery': "Batareya",
        'lbl_condition': "Holati",
        'lbl_region': "Region",
        'lbl_box': "Karobka",
        'lbl_price': "Narxi",
        'lbl_contact': "Aloqa",
        'prompt_buy_model': "📲 <b>Qaysi modeldagi iPhone qidiryapsiz?</b>",
        'prompt_buy_memory': "💾 <b>Xotira hajmini tanlang:</b>",
        'prompt_buy_color': "🎨 <b>Rangini tanlang (ixtiyoriy, 'Hammasi' deb yozishingiz mumkin):</b>",
        'prompt_buy_branch': "🏢 <b>Qaysi filialdan sotib olmoqchisiz?</b>",
        'no_results': "❌ Afsuski, qidiruvingiz bo'yicha hech narsa topilmadi.",
        'results_title': "🔎 <b>Qidiruv natijalari:</b>",
        'prompt_select_id': "📝 <b>Sotib olmoqchi bo'lgan telefon ID sini yozing:</b>",
        'err_id': "❌ Noto'g'ri ID. Iltimos, yuqoridagi ro'yxatdan ID tanlang:",
        'confirm_buy': "❓ <b>ID {id} bo'lgan telefonni buyurtma qilishni tasdiqlaysizmi?</b>",
        'buy_success': "✅ <b>Buyurtmangiz qabul qilindi!</b>\nAdmin tez orada siz bilan bog'lanadi.",
        'prompt_payment_type': "💳 <b>To'lov turini tanlang:</b>",
        'btn_cash': "💵 Naqd to'lov",
        'btn_installment': "💳 Muddatli to'lov",
        'prompt_location': "📍 <b>Qaysi hududda yashaysiz?</b>\n\n<i>Boshlang'ich to'lov miqdori shunga qarab belgilanadi:</i>",
        'btn_city': "🏙 Toshkent shahri (30%)",
        'btn_region': "🌄 Viloyat (40%)",
        'prompt_plan': "📅 <b>Oylik to'lov muddatini tanlang:</b>",
        'prompt_price_model': "📲 <b>Qaysi iPhone modelini narxlatmoqchisiz?</b>",
        'prompt_price_photos': "📸 <b>1 ta sifatli rasm yuklang:</b>",
        'prompt_price_battery': "🔋 <b>Batareya yomkostini kiriting (% da, masalan: 88):</b>",
        'prompt_price_memory': "💾 <b>Xotira hajmini tanlang:</b>",
        'prompt_price_screen_condition': "📱 <b>Ekran holati qanday?</b>",
        'prompt_price_body_condition': "📐 <b>Korpus holati qanday?</b>",
        'prompt_price_region': "🌍 <b>Regionni tanlang:</b>",
        'prompt_manual_region': "🌍 <b>Region nomini yozing:</b>",
        'prompt_price_box': "📦 <b>Karobka va hujjati bormi?</b>",
        'prompt_is_opened': "🛠 <b>Telefon ochilganmi, ustada bo'lganmi?</b>",
        'prompt_price_confirm': "✨ <i>Barchasi to'g'rimi? Ma'lumotlarni yuborishni tasdiqlaysizmi?</i>",
        'price_success': "✅ <b>Sizning telefoningiz taxminiy narxi: {price} mln so'm.</b>\n\nMutaxassislarimiz tez orada siz bilan bog'lanishadi.\n\n🔔 <i>Iltimos, bot xabarlarini kuting!</i>",
        'prompt_admin_pass': "🔑 <b>Admin panelga kirish uchun parolni kiriting:</b>",
        'admin_welcome': "🔓 <b>Xush kelibsiz, Admin!</b>\n\nFiliallarga mahsulot qo'shishingiz mumkin.",
        'err_pass': "❌ <b>Parol noto'g'ri!</b> Qaytadan urinib ko'ring yoki bekor qiling.",
        'prompt_admin_model': "📱 <b>Qo'shmoqchi bo'lgan iPhone modelini tanlang:</b>",
        'prompt_admin_branch': "🏢 <b>Qaysi filialga qo'shmoqchisiz?</b>",
        'prompt_admin_storage': "💾 <b>Xotira hajmini tanlang:</b>",
        'prompt_admin_battery': "🔋 <b>Batareya yomkostini kiriting (masalan: 95):</b>",
        'prompt_admin_condition': "🛠 <b>Holatini tanlang:</b>",
        'prompt_admin_price': "💰 <b>Sotuv narxini kiriting (masalan: 8.5 mln yoki 8 500 000 so'm):</b>",
        'prompt_admin_photos': "📸 <b>Kamida 1 ta rasm yuklang (yaxshisi 3 ta). Yuklab bo'lgach pastdagi 'Davom etish' tugmasini bosing:</b>",
        'admin_add_success': "✅ <b>Mahsulot muvaffaqiyatli filialga va Mini Appga qo'shildi!</b>",
        'admin_branch_menu': "🏢 <b>Filiallarni boshqarish menyusi:</b>",
        'prompt_branch_name': "📝 <b>Yangi filial nomini kiriting:</b>",
        'branch_added': "✅ <b>{name}</b> filiali muvaffaqiyatli qo'shildi!",
        'prompt_delete_branch': "🗑 <b>O'chirmoqchi bo'lgan filialni tanlang:</b>",
        'branch_deleted': "✅ <b>{name}</b> filiali o'chirildi!",
        'prompt_delete_model': "📱 <b>Qaysi modeldagi telefonni o'chirmoqchisiz?</b>\n(Masalan: iPhone 13 Pro Max)",
        'no_model_found': "❌ <b>Bunday modeldagi mahsulot topilmadi.</b>",
        'found_models': "🔍 <b>Topilgan mahsulotlar:</b>\n\n",
        'prompt_delete_id': "\n🔢 <b>O'chirmoqchi bo'lgan telefon ID sini kiriting:</b>",
        'ad_deleted': "✅ <b>ID {id}</b> bo'lgan mahsulot o'chirildi!",
        'prompt_ad_branch': "🏢 <b>Ushbu e'lon qaysi filialga tegishli?</b>",
        'ad_approved_user': "✅ <b>Tabriklaymiz!</b>\n\nSizning e'loningiz (ID: {id}) tasdiqlandi va <b>{branch}</b> filialiga biriktirildi. 🚀",
        'ad_approved_admin': "✅ E'lon {id} tasdiqlandi va {branch} ga qo'shildi.",
        'ad_rejected_user': "❌ <b>Afsuski...</b>\n\nSizning e'loningiz (ID: {id}) rad etildi. Ma'lumotlarni tekshirib qaytadan urinib ko'ring.",
        'ad_rejected_admin': "❌ E'lon {id} rad etildi.",
        'prompt_set_price': "💰 <b>Tasdiqlangan narxni kiriting (mln so'mda):</b>",
        'price_sent_user': "📢 <b>Admin tomonidan tasdiqlangan narx:</b>\n\n📱 Model: {model}\n💰 Yakuniy narx: <b>{price} mln so'm</b>\n\nSotishni xohlasangiz 'Telefon sotish' bo'limiga o'ting! 🚀",
        'price_sent_admin': "✅ Foydalanuvchiga narx yuborildi.",
        'prompt_counter_price': "✍️ Mijozga taklif qilmoqchi bo'lgan narxingizni yozing (masalan: 4 500 000 so'm):",
        'counter_sent_user': "📢 <b>Sizning e'loningiz bo'yicha admin taklifi:</b>\n\nAdmin siz aytgan narxga ololmaydi, lekin <b>{price}</b> narxni taklif qiladi.\n\nTaklifga rozimisiz?",
        'counter_sent_admin': "✅ Mijozga qarshi taklif yuborildi.",
        'part_battery': "Batareya",
        'part_display': "Ekran",
        'part_glass': "Orqa qopqoq",
        'part_camera': "Kamera",
        'part_audio': "Dinamik",
        'part_buttons': "Tugmalar",
        'part_other': "Boshqa",
        'part_none': "Almashtirilmagan",
        'defect_faceid': "Face ID",
        'defect_truetone': "True Tone",
        'defect_camera_front': "Old kamera",
        'defect_camera_back': "Asosiy kamera",
        'defect_audio': "Dinamiklar",
        'defect_mic': "Mikrofon",
        'defect_vibro': "Vibro",
        'defect_wifi': "Wi-Fi / Bluetooth",
        'defect_gps': "GPS",
        'defect_nfc': "NFC / Apple Pay",
        'defect_none': "Hammasi ishlaydi",
        'lbl_replaced': "Almashtirilgan",
        'lbl_defects': "Nosozliklar",
        'err_price': "❌ <b>Narx noto'g'ri kiritildi!</b>\nIltimos, aniqroq narx yozing (masalan: 8 500 000 so'm):",
        'val_none': "Yo'q",
        'prompt_esim': "📱 <b>Telefoningiz eSim'limi yoki Fizik sim'limi?</b>",
        'price_bring_user': "📢 <b>Admin taklifi:</b>\n\nSizning telefoningizni ko'rib chiqdik. Iltimos, telefonni <b>Markab Electronics</b> do'koniga olib keling, mutaxassislarimiz joyida ko'rib, aniq narxini aytishadi va sotib olamiz. 🤝\n\n📍 Manzillar: /branches",
        'msg_price_bring': "✅ Mijozga magazinga olib kelish taklifi yuborildi.",
        'msg_stats': "📊 <b>LOYIHA STATISTIKASI:</b>\n\n👤 Foydalanuvchilar: <b>{users} ta</b>\n📱 Jami e'lonlar: <b>{ads} ta</b>\n✅ Sotuvdagi telefonlar: <b>{active} ta</b>\n💰 Narxlash so'rovlari: <b>{prices} ta</b>\n🤝 Muvaffaqiyatli savdolar: <b>{sales} ta</b>\n\n📈 <i>Loyiha o'sishda davom etmoqda!</i>",
    },
    'ru': {
        'start_welcome': "Здравствуйте! Добро пожаловать в бот Markab Electronics.\nПожалуйста, выберите язык:",
        'select_lang': "🇷🇺 Русский язык",
        'sub_required': "Для использования бота необходимо подписаться на наш канал!",
        'btn_sub': "Подписаться",
        'btn_check': "Подтвердить",
        'sub_error': "Вы еще не подписались на канал. Пожалуйста, подпишитесь и нажмите кнопку 'Подтвердить' еще раз.",
        'main_menu': "Главное меню:",
        'btn_buy': "🛍 Купить телефон",
        'btn_sell': "📱 Продать телефон",
        'btn_price': "💰 Оценка",
        'btn_branches': "🏢 Наши филиалы",
        'btn_miniapp': "🌐 Мини-приложение",
        'btn_help': "ℹ️ Инфо/Помощь",
        'btn_admin': "🔐 Админ-панель",
        'btn_back': "⬅️ Назад",
        'btn_cancel': "❌ Отмена",
        'btn_confirm': "✅ Подтвердить",
        'btn_share_contact': "📞 Поделиться контактом",
        'btn_add_product': "➕ Добавить товар",
        'btn_manage_branches': "🏢 Управление филиалами",
        'btn_delete_product': "🗑 Удалить товар",
        'btn_stats': "📊 Статистика",
        'btn_exit': "⬅️ Выход",
        'btn_open_miniapp': "🌐 Открыть в Mini App",
        'btn_continue_bot': "🤖 Продолжить в боте",
        'btn_continue': "➡️ Продолжить",
        'prompt_choice': "✨ <b>Где вы хотите продолжить?</b>\n\n<i>Mini App быстрее и удобнее, а бот поможет шаг за шагом.</i>",
        'btn_add_branch': "➕ Добавить филиал",
        'btn_delete_branch': "❌ Удалить филиал",
        'btn_back_to_admin': "⬅️ Вернуться в админ-меню",
        'btn_set_price': "✍️ Написать цену",
        'btn_approve': "✅ Одобрить",
        'btn_counter': "🔄 Встречное предложение",
        'btn_reject': "❌ Отклонить",
        'msg_deleted': "🗑 Товар удален.",
        'msg_cancelled': "❌ Отменено.",
        'msg_success_add': "✅ Товар успешно добавлен!",
        'main_menu_info': "📱 Оценка вашего телефона по рыночной цене;\n🤝 Быстрая и простая продажа;\n🛍 Возможность покупки качественных телефонов.",
        'prompt_color': "🎨 <b>Выберите цвет вашего телефона:</b>",
        'prompt_cycles': "🔄 <b>Введите количество циклов батареи (например: 150):</b>",
        'prompt_replaced_parts': "🔧 <b>Замененные части:</b>\n\n<i>Отметьте замененные части и нажмите 'Давом этиш'.</i>",
        'prompt_defects': "⚠️ <b>Неисправности:</b>\n\n<i>Отметьте неисправности и нажмите 'Давом этиш'.</i>",
        'btn_yes': "✅ Да",
        'btn_no': "❌ Нет",
        'lbl_color': "Цвет",
        'lbl_cycles': "Циклы",
        'prompt_model': "📲 <b>Выберите модель iPhone для продажи:</b>",
        'prompt_photos': "📸 <b>Загрузите 1 качественное фото телефона:</b>",
        'prompt_battery': "🔋 <b>Введите емкость аккумулятора (в %, например: 88):</b>",
        'prompt_memory': "💾 <b>Выберите объем памяти:</b>",
        'prompt_screen_condition': "📱 <b>Какое состояние экрана?</b>",
        'prompt_body_condition': "📐 <b>Какое состояние корпуса (края и задняя панель)?</b>",
        'prompt_region': "🌍 <b>Выберите регион телефона:</b>",
        'prompt_box': "📦 <b>Есть ли коробка и документы?</b>",
        'prompt_is_opened': "🛠 <b>Телефон открывался, был ли в ремонте?</b>",
        'prompt_price': "💰 <b>Введите цену, за которую хотите продать (например: 8 500 000 сум или 8.5 млн):</b>",
        'prompt_description': "📝 <b>Напишите дополнительную информацию о телефоне (необязательно, можно написать 'Пропустить'):</b>",
        'prompt_confirm': "✨ <i>Все верно? Подтверждаете?</i>",
        'summary_title': "<b>📋 Данные вашего объявления:</b>",
        'sell_success': "✅ <b>Ваше объявление принято!</b>\n\nПримерная рыночная цена вашего телефона: <b>{price} млн сум</b>.\n\nНаши админы скоро рассмотрят его и разместят в канале.",
        'err_battery': "❌ Пожалуйста, введите корректный процент (1-100):",
        'lbl_model': "Модель",
        'lbl_memory': "Память",
        'lbl_battery': "Батарея",
        'lbl_condition': "Состояние",
        'lbl_region': "Регион",
        'lbl_box': "Коробка",
        'lbl_price': "Цена",
        'lbl_contact': "Связь",
        'prompt_contact': "📞 <b>Отправьте ваш номер телефона для связи:</b>",
        'err_price': "❌ <b>Некорректная цена!</b>\nПожалуйста, введите точную цену (например: 8 500 000 сум):",
        'prompt_buy_model': "📲 <b>Какую модель iPhone вы ищете?</b>",
        'prompt_buy_branch': "🏢 <b>В каком филиале хотите купить?</b>",
        'prompt_buy_memory': "💾 <b>Выберите объем памяти:</b>",
        'prompt_buy_color': "🎨 <b>Выберите цвет (необязательно, можно написать 'Все'):</b>",
        'no_results': "❌ К сожалению, по вашему запросу ничего не найдено.",
        'results_title': "🔎 <b>Результаты поиска:</b>",
        'prompt_select_id': "📝 <b>Напишите ID телефона, который хотите купить:</b>",
        'err_id': "❌ Неверный ID. Пожалуйста, выберите ID из списка выше:",
        'confirm_buy': "❓ <b>Подтверждаете заказ телефона с ID {id}?</b>",
        'buy_success': "✅ <b>Ваш заказ принят!</b>\nАдмин скоро свяжется с вами.",
        'prompt_payment_type': "💳 <b>Выберите тип оплаты:</b>",
        'btn_cash': "💵 Наличные",
        'btn_installment': "💳 В рассрочку",
        'prompt_location': "📍 <b>В каком регионе вы проживаете?</b>\n\n<i>Первоначальный взнос зависит от вашего региона:</i>",
        'btn_city': "🏙 Город Ташкент (30%)",
        'btn_region': "🌄 Область (40%)",
        'prompt_plan': "📅 <b>Выберите срок оплаты:</b>",
        'prompt_price_model': "📲 <b>Какую модель iPhone вы хотите оценить?</b>",
        'prompt_price_photos': "📸 <b>Отправьте 1 качественное фото телефона:</b>",
        'prompt_price_battery': "🔋 <b>Выберите емкость аккумулятора:</b>",
        'prompt_price_memory': "💾 <b>Выберите объем памяти:</b>",
        'prompt_price_screen_condition': "📱 <b>Какое состояние экрана?</b>",
        'prompt_price_body_condition': "📐 <b>Какое состояние корпуса?</b>",
        'prompt_price_region': "🌍 <b>Выберите регион:</b>",
        'prompt_price_box': "📦 <b>Есть ли коробка и документы?</b>",
        'prompt_is_opened': "🛠 <b>Телефон открывался, был ли в ремонте?</b>",
        'prompt_manual_region': "🌍 <b>Напишите название региона:</b>",
        'prompt_price_confirm': "✨ <i>Все верно? Подтверждаете отправку данных?</i>",
        'price_success': "✅ <b>Примерная стоимость вашего телефона: {price} млн сум.</b>\n\nНаши специалисты скоро свяжутся с вами.\n\n🔔 <i>Пожалуйста, ждите сообщения от бота!</i>",
        'prompt_admin_pass': "🔑 <b>Введите пароль для входа в админ-панель:</b>",
        'admin_welcome': "🔓 <b>Добро пожаловать, Админ!</b>\n\nВы можете добавлять товары в филиалы.",
        'err_pass': "❌ <b>Неверный пароль!</b> Попробуйте еще раз или отмените.",
        'prompt_admin_model': "📱 <b>Выберите модель iPhone для добавления:</b>",
        'prompt_admin_branch': "🏢 <b>В какой филиал хотите добавить?</b>",
        'prompt_admin_storage': "💾 <b>Выберите объем памяти:</b>",
        'prompt_admin_battery': "🔋 <b>Введите емкость аккумулятора (например: 95):</b>",
        'prompt_admin_condition': "🛠 <b>Выберите состояние:</b>",
        'prompt_admin_price': "💰 <b>Введите цену продажи (например: 8.5 млн или 8 500 000 сум):</b>",
        'prompt_admin_photos': "📸 <b>Отправьте фото товара (минимум 1):</b>",
        'admin_add_success': "✅ <b>Товар успешно добавлен в филиал и Мини-приложение!</b>",
        'admin_branch_menu': "🏢 <b>Меню управления филиалами:</b>",
        'prompt_branch_name': "📝 <b>Введите название нового филиала:</b>",
        'branch_added': "✅ Филиал <b>{name}</b> успешно добавлен!",
        'prompt_delete_branch': "🗑 <b>Выберите филиал для удаления:</b>",
        'branch_deleted': "✅ Филиал <b>{name}</b> удален!",
        'prompt_delete_model': "📱 <b>Какую модель телефона вы хотите удалить?</b>\n(Например: iPhone 13 Pro Max)",
        'no_model_found': "❌ <b>Товар такой модели не найден.</b>",
        'found_models': "🔍 <b>Найденные товары:</b>\n\n",
        'prompt_delete_id': "\n🔢 <b>Введите ID телефона для удаления:</b>",
        'ad_deleted': "✅ Товар с <b>ID {id}</b> удален!",
        'prompt_ad_branch': "🏢 <b>К какому филиалу относится это объявление?</b>",
        'ad_approved_user': "✅ <b>Поздравляем!</b>\n\nВаше объявление (ID: {id}) одобрено и привязано к филиалу <b>{branch}</b>. 🚀",
        'ad_approved_admin': "✅ Объявление {id} одобрено и добавлено в {branch}.",
        'ad_rejected_user': "❌ <b>К сожалению...</b>\n\nВаше объявление (ID: {id}) отклонено. Проверьте данные и попробуйте еще раз.",
        'ad_rejected_admin': "❌ Объявление {id} отклонено.",
        'prompt_set_price': "💰 <b>Введите утвержденную цену (в млн сум):</b>",
        'price_sent_user': "📢 <b>Цена, утвержденная админом:</b>\n\n📱 Модель: {model}\n💰 Итоговая цена: <b>{price} млн сум</b>\n\nЕсли хотите продать, перейдите в раздел 'Продать телефон'! 🚀",
        'price_sent_admin': "✅ Цена отправлена пользователю.",
        'prompt_counter_price': "✍️ Введите цену, которую хотите предложить клиенту (например: 4 500 000 сум):",
        'counter_sent_user': "📢 <b>Предложение админа по вашему объявлению:</b>\n\nАдмин не может купить по вашей цене, но предлагает <b>{price}</b>.\n\nСогласны?",
        'counter_sent_admin': "✅ Встречное предложение отправлено пользователю.",
        'part_battery': "Батарея",
        'part_display': "Экран",
        'part_glass': "Задняя крышка",
        'part_camera': "Камера",
        'part_audio': "Динамик",
        'part_buttons': "Кнопки",
        'part_other': "Другое",
        'part_none': "Не менялось",
        'defect_faceid': "Face ID",
        'defect_truetone': "True Tone",
        'defect_camera_front': "Передняя камера",
        'defect_camera_back': "Основная камера",
        'defect_audio': "Динамики",
        'defect_mic': "Микрофон",
        'defect_vibro': "Вибро",
        'defect_wifi': "Wi-Fi / Bluetooth",
        'defect_gps': "GPS",
        'defect_nfc': "NFC / Apple Pay",
        'defect_none': "Все работает",
        'lbl_replaced': "Заменено",
        'lbl_defects': "Дефекты",
        'val_none': "Нет",
        'prompt_esim': "📱 <b>Ваш телефон с eSim или Физической сим-картой?</b>",
        'price_bring_user': "📢 <b>Предложение админа:</b>\n\nМы рассмотрели ваш запрос. Пожалуйста, принесите телефон в магазин <b>Markab Electronics</b>, наши специалисты осмотрят его на месте, назовут точную цену и мы его выкупим. 🤝\n\n📍 Адреса: /branches",
        'msg_price_bring': "✅ Клиенту отправлено предложение прийти в магазин.",
        'msg_stats': "📊 <b>СТАТИСТИКА ПРОЕКТА:</b>\n\n👤 Пользователей: <b>{users}</b>\n📱 Всего объявлений: <b>{ads}</b>\n✅ Телефонов в продаже: <b>{active}</b>\n💰 Запросов на оценку: <b>{prices}</b>\n🤝 Успешных сделок: <b>{sales}</b>\n\n📈 <i>Проект продолжает расти!</i>",
    }
}
