# Generated by Django 6.0.1 on 2026-05-02 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('is_installment', models.BooleanField(default=False)),
                ('installment_months', models.IntegerField(blank=True, null=True)),
                ('delivery_type', models.CharField(choices=[('pickup', 'Kelib olib ketish'), ('delivery', 'Dastavka')], default='pickup', max_length=20)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='phones.listing')),
            ],
        ),
    ]
