# Generated by Django 6.0.1 on 2026-05-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='initial_payment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
